"""
backend/auth/id_card.py

Layer 2 of the login pipeline: physical ID card with an embedded QR code.

The QR code does NOT just encode the employee_id in the clear -- that would
let anyone photocopy a card and forge one. Instead it encodes an HMAC-signed
payload, so a card can only be "valid" if it was generated by the server
that holds CARD_SIGNING_SECRET.

Flow:
  1. (provisioning time) generate_employee_qr() -- makes the QR PNG that gets
     printed onto the physical card.
  2. (login time) verify_id_card_scan() -- the scanned QR string is checked
     for a valid signature, non-expiry, and that it matches the employee
     who just passed layer 1.
"""

import os
import json
import hmac
import hashlib
import base64
import uuid
import qrcode
from datetime import datetime, timezone, timedelta

from .models import StageToken, LoginStage, LoginResult
from .credentials import verify_stage_token, issue_stage_token

CARD_SIGNING_SECRET = os.environ.get("MEDILINK_CARD_SECRET", "dev-card-secret-change-me").encode()
CARD_VALIDITY_DAYS = 365   # how long a printed card stays valid before reissue


def _sign(payload_bytes: bytes) -> str:
    return hmac.new(CARD_SIGNING_SECRET, payload_bytes, hashlib.sha256).hexdigest()


def _encode_card_payload(employee_id: str) -> str:
    """Builds the exact string that gets embedded in the QR code."""
    data = {
        "employee_id": employee_id,
        "issued_at": datetime.now(timezone.utc).isoformat(),
        "card_id": str(uuid.uuid4()),   # unique per physical card, lets you revoke one card without affecting others
    }
    payload_bytes = json.dumps(data, sort_keys=True).encode()
    payload_b64 = base64.urlsafe_b64encode(payload_bytes).decode()
    signature = _sign(payload_bytes)
    return f"{payload_b64}.{signature}"


def _decode_and_verify_card_payload(qr_string: str) -> dict:
    payload_b64, signature = qr_string.rsplit(".", 1)
    payload_bytes = base64.urlsafe_b64decode(payload_b64.encode())
    expected_signature = _sign(payload_bytes)
    if not hmac.compare_digest(signature, expected_signature):
        raise ValueError("Card signature invalid -- possible forged/tampered card.")

    data = json.loads(payload_bytes)
    issued_at = datetime.fromisoformat(data["issued_at"])
    if datetime.now(timezone.utc) - issued_at > timedelta(days=CARD_VALIDITY_DAYS):
        raise ValueError("Card has expired -- reissue required.")

    return data


# ---------------------------------------------------------------------------
# Provisioning-time: generate the QR code image for printing on a card
# ---------------------------------------------------------------------------
def generate_employee_qr(employee_id: str, output_path: str) -> str:
    """Creates the QR PNG to be printed on the physical demo ID card.
    Returns the raw card payload string too, in case you want to log it."""
    card_string = _encode_card_payload(employee_id)

    img = qrcode.make(card_string, box_size=10, border=2)
    img.save(output_path)
    return card_string


# ---------------------------------------------------------------------------
# Login-time: verify a scanned QR against the employee who passed layer 1
# ---------------------------------------------------------------------------
def verify_id_card_scan(stage2_token: str, scanned_qr_string: str) -> LoginResult:
    try:
        stage_token: StageToken = verify_stage_token(stage2_token, LoginStage.STAGE2_ID_CARD)
    except Exception:
        return LoginResult(success=False, stage=LoginStage.STAGE2_ID_CARD,
                            message="Session expired or invalid. Please log in again.")

    try:
        card_data = _decode_and_verify_card_payload(scanned_qr_string)
    except ValueError as e:
        return LoginResult(success=False, stage=LoginStage.STAGE2_ID_CARD, message=str(e))

    if card_data["employee_id"] != stage_token.employee_id:
        return LoginResult(success=False, stage=LoginStage.STAGE2_ID_CARD,
                            message="This ID card does not belong to the logged-in user.")

    nonce = str(uuid.uuid4())
    token = issue_stage_token(stage_token.employee_id, LoginStage.STAGE3_FACIAL, nonce)
    return LoginResult(
        success=True,
        stage=LoginStage.STAGE3_FACIAL,
        message="ID card verified. Please complete facial recognition.",
        token=token,
    )
